### ISSUE TITLE
Is macOS support included?

### ISSUE THREAD

**Issue by gotoolkits** [apinge/MeloTTS.cpp#20]
Is macOS support included?

**Comment by apinge** [comment]
In theory, I think it can support macOS because the OpenVINO C++ package supports macOS.  However, we don't have any Mac device 😅 , so we don't plan to support macOS in this repo. 

You can follow this guide https://docs.openvino.ai/2024/get-started/install-openvino/install-openvino-vcpkg.html or download it directly from https://storage.openvinotoolkit.org/repositories/openvino/packages/2024.4/macos/
Generally, macOS might have specific compilation options or require some code modifications.  If you could give it a try and encounter any issues, you can raise an issue here or ask in the OpenVINO toolkit.
We also welcome you to fork a branch to make your own modifications.
